services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: ${DOCKER_STAGE_TARGET:-dev}
    image: ${DOCKER_IMAGE:-platform:local}
    command: bin/rails server --binding 0.0.0.0
    entrypoint: bin/docker-web-entrypoint.sh
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app

  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_cache:
