name: CI

on: push

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx to be able to use caching
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.dev
          cache-from: type=gha
          cache-to: type=gha
